#generic example of the yaml template
quantitative_feature: 
  type: scalar
  template: Text describing the {value} of the quantitative feature


boolean: 
  type: boolean
  yes: Text to apply if the feature has the value true
  no: Text to apply if the feature has the value false